### ISSUE TITLE
Glitches occures in the battle screen

### ISSUE THREAD

**Issue by thomas-w-holleis** [Pyrdacor/Ambermoon-Advanced#5] opened 2022-06-10 20:32 UTC
On the battle screen some glitches happen on the enemy graphics. Sometimes on the left and/or right side of the enemy and sometimes on the whole graphic of the enemy.
See screenshots

![Ambermoon-Advanced-0 0 1-Anzeigefehler_Kampf-Feuerriese-Bollgartunnel](https://user-images.githubusercontent.com/20624618/173145440-f8c28ab9-065a-4aa4-9284-8d54531273ad.png)
![Ambermoon-Advanced-0 0 1-Anzeigefehler_Kampf](https://user-images.githubusercontent.com/20624618/173145444-c475e73a-06c9-443a-958f-c90f6a07e833.png)

Run Ambermoon Advanced v00.10 with FS-UAE 2.8.3 on macOS Sierra 10.12.6

**Comment by Pyrdacor** [comment] 2022-06-10 20:36
Thanks. This is a known issue. I will investigate this.

**Comment by macce2** [comment] 2022-10-21 20:36
QUOTE: 
thomas-w-holleis wrote:

"On the battle screen some glitches happen on the enemy graphics. Sometimes on the left and/or right side of the enemy and sometimes on the whole graphic of the enemy."
/QUOTE

I'm experiencing similar glitches.
They seem to be more regular when there's more than two enemies on the screen;
and especially when there's bandits.
Running Ambermoon Advanced v00.10 on classic Amiga4000D (060@50) OS3.9 system.

**Comment by Pyrdacor** [comment] 2022-10-21 20:56
Thanks. Currently I finalize last content additions and some code adjustments. After that I will focus on bug fixing including this issue.

**Comment by macce2** [comment] 2022-11-09 19:48
In my case; 
I found out one strange thing.
If Nelvin casts a magical missile spell,
there's a vertical "border bar" like glitch , which makes the missile
partly corrupt; when it is about to be shooted.
But that only appears, if Nelvin is situated so that the missile is being shooted 
from the left side of the battle screen;
it doesn't seem to appear at the right side at all..?!
So; some kind of invisible "border" ; which appears on the left side of the
screen and corrupts evrything that it covers;
but it seems to be noticeably narrow area of the battle screen.
That glitch only seems to occur; when something is being shooted
from the left.

Oh, and when a battle is won ; often (not always) there's a similar kind of 
vertical line glitch on the right side of the screen.
During battles, I have found out that the enemy sprites are more likely
to have graphics corruption(-s), when they are near the party members /
advancing closer; and/or moving there.
And the more "complex" or large the enemy sprite(-s), the more likely
those glitches seem to occur.
I thought I Must tell this detail, as it may be potentially relevant info.
Sorry for my English.

**Comment by Pyrdacor** [comment] 2022-11-09 21:18
Thank you for the additional details. I will try to reproduce this in the next few days and work on a fix

**Comment by Pyrdacor** [comment] 2022-11-15 10:30
Hm I could reproduce this with bandits in Spannenberg. But only with episode I. I could not reproduce it with the current state of episode II, even with the same savegame. Either it was somehow fixed by mistake or it is bad luck.

**Comment by macce2** [comment] 2022-11-23 16:19
Good to hear that.
Hopefully, it will get fixed !

**Comment by Pyrdacor** [comment] 2022-11-23 20:10
If you would like to beta test, we could find out early. ;)

**Comment by macce2** [comment] 2022-11-23 21:24
Hello Robert,

Thank You, sure I'd like to beta-test.
However, I think You'd better give me
some directions, then !?

Regards,

Marko

ke 23. mar 2022 klo 22.10 Pyrdacor ***@***.***> kirjoitti:

**Comment by Pyrdacor** [comment] 2022-11-24 06:02
Hi Marko,

the main problem at the moment is, that the English translation isn't done yet. But you could already go to Spannenberg, fight a few bandits and see if the glitch is still there.

**Comment by Pyrdacor** [comment] 2022-11-24 06:03
I could prepare a package for you with the latest data.

**Comment by macce2** [comment] 2022-11-24 14:13
Hi,

Thanks. Yes; the german language version is ok !
Would You upload the needed file(-s) or send them to me directly ..?!
Im soon ready to do some testing
and thankful for given the honour to do so ☺.


Marko

to 24. mar 2022 klo 8.03 Pyrdacor ***@***.***> kirjoitti:

**Comment by macce2** [comment] 2022-11-24 20:42
Party suffers energy loss near the tower of alchemist
            (northside); there appears not any condition.

            After some party members died there; when trying to quit the
game,
            a crash with reboot.
            Couldnt repeat the crash.


            After leaving the alchemist tower the second time; graphics
corrupted on the
            main view screen 2D.

to 24. marrask. 2022 klo 16.12 macce2 ***@***.***) kirjoitti:

**Comment by macce2** [comment] 2022-11-25 11:38
Sorry for double- posting accidentally.
If I understood right ( the package behind the Code option of GH ..?!?) waz
the one for me to download...?!
If so; Im sorry to report: Yes, theres still graphics glitches on the
battle screen.
Sorry for the late reply ! ( Im new to GitHub)

to 24. mar 2022 klo 22.42 macce2 ***@***.***> kirjoitti:

**Comment by Pyrdacor** [comment] 2022-11-25 14:10
I didn't pack anything yet. Want to take care of a few things first. I will let you know and send you a zip file then directly.

**Comment by Pyrdacor** [comment] 2022-12-13 13:30
According to @macce2 's tests this issues is fixed in the second episode.

**Closed** 2023-02-17 21:04 UTC
Labels: bug, fixed
